name: Action tp2
on:
  workflow_dispatch:
    inputs:
      serveur:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Demarrage
        run: echo "Démarrage sur ${{ github.ref }}"

      - name : Checkout
        if: ${{github.ref == 'refs/heads/main'}}
        uses: actions/checkout@v4.1.1

      - name : Deploiement production
        run: echo "deploiement en prod"
